/**
 * Copyright (c) 2021-Present, Nitrogen Labs, Inc.
 * Copyrights licensed under the MIT License. See the accompanying LICENSE file for terms.
 */

export const MetropolisConstants = {
  INITIALIZE: 'METROPOLIS_APP_INITIALIZE',
  LOADING: 'METROPOLIS_APP_LOADING',
  SIGNOUT: 'METROPOLIS_APP_SIGNOUT',
  SUBSCRIBE_MESSAGES: 'METROPOLIS_APP_SUBSCRIBE_MESSAGES',
  SUBSCRIBE_NOTIFICATIONS: 'METROPOLIS_APP_SUBSCRIBE_NOTIFICATIONS',
  UPDATE_MESSAGES: 'METROPOLIS_APP_UPDATE_MESSAGES',
  UPDATE_NOTIFICATIONS: 'METROPOLIS_APP_UPDATE_NOTIFICATIONS',
  UPDATE_SESSION: 'METROPOLIS_APP_UPDATE_SESSION'
};
