export const REACTION_ADD_SUCCESS: string = 'REACTION_ADD_SUCCESS';
export const REACTION_ADD_ERROR: string = 'REACTION_ADD_ERROR';
export const REACTION_DELETE_SUCCESS: string = 'REACTION_REMOVE_SUCCESS';
export const REACTION_DELETE_ERROR: string = 'REACTION_DELETE_ERROR';
export const REACTION_COUNT_SUCCESS: string = 'REACTION_COUNT_SUCCESS';
export const REACTION_COUNT_ERROR: string = 'REACTION_COUNT_ERROR';
export const REACTION_HAS_SUCCESS: string = 'REACTION_COUNT_SUCCESS';
export const REACTION_HAS_ERROR: string = 'REACTION_COUNT_ERROR';
